// выводит пункты выдачи
let renderDeliveryPoints = (deliveryPoints) => {
    
    let deliveryPoints = [
        {
            "code": "ORN58",
            "uuid": "1fd6a616-2716-4c82-947e-71f6cff3998d",
            "name": "На Березовой Ростоши 11",
            "address_comment": "От остановки Поликлиника 610 метров через Ледовый дворец",
            "nearest_station": "Поликлиника",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+79228496091,",
            "email": "e.ostrouhova@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 50.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460008,
            "latitude": 51.78345,
            "longitude": 55.22484,
            "address": "ул. Березовая Ростошь, 11",
            "address_full": "460008, Россия, Оренбургская область, Оренбург, ул. Березовая Ростошь, 11"
        },
        {
            "code": "ORN4",
            "uuid": "7e82a1e9-8261-4b32-8257-1cc3856b8789",
            "name": "На Цвиллинга",
            "address_comment": "Справа по улице Цвиллинга от улицы Постникова сразу за магазином игрушек «ЛИМПОПО», в 100 метрах от остановки общественного транспорта «Постникова» по ул. Цвиллинга.",
            "nearest_station": "Постникова",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+79619069252,",
            "email": "r.kinzyagulov@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 70.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460000,
            "latitude": 51.772804,
            "longitude": 55.09374,
            "address": "ул. Цвиллинга, 32",
            "address_full": "460000, Россия, Оренбургская область, Оренбург, ул. Цвиллинга, 32"
        },
        {
            "code": "ORN22",
            "uuid": "67797700-4b09-4fde-a643-e2bd48b8ebcc",
            "name": "На Славянском рынке",
            "address_comment": "Славянский рынок",
            "nearest_station": "Остановка Славянский рынок",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+79877991010,",
            "email": "e.shlyapnikova@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 100.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460003,
            "latitude": 51.785027,
            "longitude": 55.07705,
            "address": "ул. Братьев Коростылевых, 1",
            "address_full": "460003, Россия, Оренбургская область, Оренбург, ул. Братьев Коростылевых, 1"
        },
        {
            "code": "ORN2",
            "uuid": "7a031057-adc0-4f1f-ad71-1907f7dc7497",
            "name": "На Салмышской",
            "address_comment": "За боулинг-центром «Рина», торгово-офисное здание «Омега».",
            "nearest_station": "Липовая",
            "work_time": "Пн-Пт 09:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+73532665444,",
            "email": "director-orenburg@edostavka.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 35.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460000,
            "latitude": 51.82754,
            "longitude": 55.158257,
            "address": "ул. Салмышская, 34/5, 101",
            "address_full": "460000, Россия, Оренбургская область, Оренбург, ул. Салмышская, 34/5, 101"
        },
        {
            "code": "ORN12",
            "uuid": "d0cfb1af-1c85-41b2-89e9-3a3bb3083815",
            "name": "На Мира",
            "address_comment": "Через дорогу от Национальной Деревни. Ближайшие остановки Национальная деревня и пр.Гагарина.",
            "nearest_station": "Национальная деревня",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+79328438434,",
            "email": "e.ostrouhova@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 50.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460040,
            "latitude": 51.7785,
            "longitude": 55.17121,
            "address": "Ул.Мира, 10",
            "address_full": "460040, Россия, Оренбургская область, Оренбург, Ул.Мира, 10"
        },
        {
            "code": "ORN6",
            "uuid": "83eaa33b-3198-4379-bf71-72ea7c593f8a",
            "name": "На Терешковой",
            "address_comment": "Расположен на перекрестке ул Терешковой и ул Хабаровской",
            "nearest_station": "Хабаровская",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+79228438438,",
            "email": "e.ostrouhova@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 35.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460050,
            "latitude": 51.818066,
            "longitude": 55.10674,
            "address": "ул. Терешковой, 263/4",
            "address_full": "460050, Россия, Оренбургская область, Оренбург, ул. Терешковой, 263/4"
        },
        {
            "code": "ORN73",
            "uuid": "8c9a11c3-421d-48bf-8137-6ca3b2433be8",
            "name": "5256 Постамат Халва",
            "address_comment": "Почтомат Халва. Войти на рынок Локомотив через отдельный вход с вывеской Ярмарка, на 1 этаже в павильоне №5 расположен почтомат.",
            "nearest_station": "Остановка Рынок Локомотив",
            "work_time": "Пн-Вс 09:00-20:00",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 15.0,
            "postamat_width": 35,
            "postamat_height": 45,
            "postamat_depth": 38,
            "postal_code": 460006,
            "latitude": 51.76975,
            "longitude": 55.077374,
            "address": "мкр. Аренда, -",
            "address_full": "460006, Россия, Оренбургская область, Оренбург, мкр. Аренда, -"
        },
        {
            "code": "ORN56",
            "uuid": "bca0dc0c-56da-48e7-b666-afa2459f1ba6",
            "name": "1943 Постамат Халва",
            "address_comment": "Войти в супермаркет Магнит Косметик через центральный вход, на 1 этаже около входа расположен постамат",
            "nearest_station": "Школа",
            "work_time": "Пн-Вс 09:30-19:30",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 30.0,
            "postamat_width": 32,
            "postamat_height": 39,
            "postamat_depth": 42,
            "postal_code": 460052,
            "latitude": 51.836643,
            "longitude": 55.159557,
            "address": "ул. Просторная, 21/1",
            "address_full": "460052, Россия, Оренбургская область, Оренбург, ул. Просторная, 21/1"
        },
        {
            "code": "ORN21",
            "uuid": "41c02e31-877b-4039-8257-2f603274a025",
            "name": "На Победы, 75",
            "address_comment": "Слева от остановки «Дом памяти» по направлению к центру города, в 30 метрах от остановки. Единый вход с «Медикал Он групп»",
            "nearest_station": "Дом памяти",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+79619069252,",
            "email": "r.kinzyagulov@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 50.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460000,
            "latitude": 51.78288,
            "longitude": 55.11522,
            "address": "пр-т. Победы, 75Е",
            "address_full": "460000, Россия, Оренбургская область, Оренбург, пр-т. Победы, 75Е"
        },
        {
            "code": "ORN70",
            "uuid": "85ae9139-1063-42ab-acb6-3d3f8842c7c6",
            "name": "6055 Постамат Халва",
            "address_comment": "Войти в магазин Красное Белое через центральный вход, на 1 этаже около входа расположен постамат.",
            "nearest_station": "ул. Рыбаковская",
            "work_time": "Пн-Вс 09:00-22:05",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 15.0,
            "postamat_width": 35,
            "postamat_height": 45,
            "postamat_depth": 38,
            "postal_code": 460006,
            "latitude": 51.774956,
            "longitude": 55.09905,
            "address": "ул. Комсомольская, 85",
            "address_full": "460006, Россия, Оренбургская область, Оренбург, ул. Комсомольская, 85"
        },
        {
            "code": "ORN49",
            "uuid": "562553e5-6c1b-458f-b30a-8854ab9b5aac",
            "name": "1942 Постамат Халва",
            "address_comment": "Магнит Косметик",
            "nearest_station": "Северный проезд",
            "work_time": "Пн-Вс 10:00-19:30",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 30.0,
            "postamat_width": 32,
            "postamat_height": 39,
            "postamat_depth": 42,
            "postal_code": 460052,
            "latitude": 51.82656,
            "longitude": 55.148502,
            "address": "ул. Брестская, 7/2",
            "address_full": "460052, Россия, Оренбургская область, Оренбург, ул. Брестская, 7/2"
        },
        {
            "code": "ORN63",
            "uuid": "8f732ece-38ec-43c1-a82c-6533655e4819",
            "name": "1959 Постамат Халва",
            "address_comment": "Войти в супермаркет Магнит Косметик через центральный вход, на 1 этаже около входа расположен постамат",
            "nearest_station": "24-ый микрорайон",
            "work_time": "Пн-Вс 10:00-19:30",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 15.0,
            "postamat_width": 32,
            "postamat_height": 39,
            "postamat_depth": 42,
            "postal_code": 460048,
            "latitude": 51.771297,
            "longitude": 55.187714,
            "address": "пр-т. Гагарина, 45/1",
            "address_full": "460048, Россия, Оренбургская область, Оренбург, пр-т. Гагарина, 45/1"
        },
        {
            "code": "ORN61",
            "uuid": "d909840d-e8bb-45da-a005-f0cb920200b1",
            "name": "1962 Постамат Халва",
            "address_comment": "Войти в супермаркет Магнит Косметик через центральный вход, на 1 этаже около входа расположен постамат.",
            "nearest_station": "Завод ЖБИ",
            "work_time": "Пн-Вс 10:00-19:30",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 15.0,
            "postamat_width": 32,
            "postamat_height": 39,
            "postamat_depth": 42,
            "postal_code": 460009,
            "latitude": 51.787495,
            "longitude": 55.04355,
            "address": "ул. Магистральная, 1",
            "address_full": "460009, Россия, Оренбургская область, Оренбург, ул. Магистральная, 1"
        },
        {
            "code": "ORN68",
            "uuid": "d908392f-faa5-4d76-a99f-4470abe9bd78",
            "name": "5615 Постамат Халва",
            "address_comment": "Войти в ТРЦ Север через центральный вход, на 1 этаже в отделении банка Совкомбанк расположен постамат.",
            "nearest_station": "Проспект Дзержинского",
            "work_time": "Пн-Вс 10:00-20:00",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 15.0,
            "postamat_width": 35,
            "postamat_height": 45,
            "postamat_depth": 38,
            "postal_code": 460044,
            "latitude": 51.833427,
            "longitude": 55.128838,
            "address": "пр-т Дзержинского, 23",
            "address_full": "460044, Россия, Оренбургская область, Оренбург, пр-т Дзержинского, 23"
        },
        {
            "code": "ORN69",
            "uuid": "30a5a60b-cbb3-497f-b68c-8b67cd32a9a2",
            "name": "5644 Постамат Халва",
            "address_comment": "Войти в магазин Студия Климота через центральный вход, на 1 этаже около входа расположен постамат.",
            "nearest_station": "Магазин Старт",
            "work_time": "Пн-Пт 09:00-18:00, Сб 10:00-16:00",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 15.0,
            "postamat_width": 35,
            "postamat_height": 45,
            "postamat_depth": 38,
            "postal_code": 460000,
            "latitude": 51.766415,
            "longitude": 55.106243,
            "address": "ул. Краснознамённая, 43/1",
            "address_full": "460000, Россия, Оренбургская область, Оренбург, ул. Краснознамённая, 43/1"
        },
        {
            "code": "ORN46",
            "uuid": "0e6fd15f-cbb1-4af0-bdce-87674aaf3e10",
            "name": "5391 Постамат Халва",
            "address_comment": "Фикс прайс, 2-й этаж",
            "nearest_station": "Национальная деревня",
            "work_time": "Пн-Вс 09:00-21:00",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 30.0,
            "postamat_width": 35,
            "postamat_height": 45,
            "postamat_depth": 38,
            "postal_code": 460040,
            "latitude": 51.774498,
            "longitude": 55.166855,
            "address": "ул.Алтайская, 2/1",
            "address_full": "460040, Россия, Оренбургская область, Оренбург, ул.Алтайская, 2/1"
        },
        {
            "code": "ORN18",
            "uuid": "362725d9-27d7-437a-b7c0-add93ca04080",
            "name": "На Поляничко",
            "address_comment": "Вход с внешней стороны дома",
            "nearest_station": "ТСЖ Звездный",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+79096000757,",
            "email": "i.nadein@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 100.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460060,
            "latitude": 51.82182,
            "longitude": 55.173607,
            "address": "ул. Поляничко, 10 пом. 12",
            "address_full": "460060, Россия, Оренбургская область, Оренбург, ул. Поляничко, 10 пом. 12"
        },
        {
            "code": "ORN15",
            "uuid": "abc36fbc-1503-47ac-a4b2-595b793e0523",
            "name": "ТК КИТ",
            "address_comment": "300М от ТК Кит, ближайшая остановка общ. Транспорта ТК Кит, жилой дом с административными помещениями,крыльцо на территории стоянки.",
            "nearest_station": "ТК Кит, автобсы №20,40,51,52,59,28,49,62",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+73532901033,",
            "email": "orenburg@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 300.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460060,
            "latitude": 51.813488,
            "longitude": 55.17748,
            "address": "ул. Салмышская, 67",
            "address_full": "460060, Россия, Оренбургская область, Оренбург, ул. Салмышская, 67"
        },
        {
            "code": "ORN44",
            "uuid": "d2c93162-333c-4494-afee-44c875efbca0",
            "name": "1949 Постамат Халва",
            "address_comment": "Магнит Косметик",
            "nearest_station": "Завод Металлист",
            "work_time": "Пн-Вс 10:00-21:00",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 30.0,
            "postamat_width": 32,
            "postamat_height": 39,
            "postamat_depth": 42,
            "postal_code": 460014,
            "latitude": 51.756878,
            "longitude": 55.09356,
            "address": "переулок  Диспансерный, 10",
            "address_full": "460014, Россия, Оренбургская область, Оренбург, переулок  Диспансерный, 10"
        },
        {
            "code": "ORN43",
            "uuid": "abd7d85c-b688-4c12-8a8c-28280cc9f8fb",
            "name": "1954 Постамат Халва",
            "address_comment": "Магнит Косметик",
            "nearest_station": "Фабрика пуховых платков",
            "work_time": "Пн-Вс 09:30-21:00",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 30.0,
            "postamat_width": 32,
            "postamat_height": 39,
            "postamat_depth": 42,
            "postal_code": 460026,
            "latitude": 51.788723,
            "longitude": 55.14605,
            "address": "ул. Марины Расковой, 10А",
            "address_full": "460026, Россия, Оренбургская область, Оренбург, ул. Марины Расковой, 10А"
        },
        {
            "code": "ORN65",
            "uuid": "22cfd3c3-b99e-42fb-bf4a-7b810b6639c0",
            "name": "3334 Постамат Халва",
            "address_comment": "Войти в ТЦ Клондайк через центральный вход, на 1 этаже в супермаркете Магнит Косметик расположен постамат.",
            "nearest_station": "Магазин Клондайк",
            "work_time": "Пн-Вс 09:00-21:00",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 15.0,
            "postamat_width": 35,
            "postamat_height": 45,
            "postamat_depth": 38,
            "postal_code": 460034,
            "latitude": 51.721092,
            "longitude": 55.113827,
            "address": "ул. Беляевская, 19",
            "address_full": "460034, Россия, Оренбургская область, Оренбург, ул. Беляевская, 19"
        },
        {
            "code": "ORN17",
            "uuid": "e2de126c-1f4d-4687-9529-48415e724a49",
            "name": "На Нижнем",
            "address_comment": "900м от СК Олимпийский, бл.остановка Пролетарская, жилой дом с административными помещениями, вход с ул.Прохоренко",
            "nearest_station": "Пролетарская автобусы:27,28,32,33,39,67 троллейбус",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+73532901015,",
            "email": "orenburg@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 50.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460050,
            "latitude": 51.80502,
            "longitude": 55.100582,
            "address": "Проезд Нижний, 8/1",
            "address_full": "460050, Россия, Оренбургская область, Оренбург, Проезд Нижний, 8/1"
        },
        {
            "code": "ORN54",
            "uuid": "7e8eeb68-3e2e-4351-9fec-d7b74ed8b09e",
            "name": "1955 Постамат Халва",
            "address_comment": "Магнит Косметик",
            "nearest_station": "Культурная улица",
            "work_time": "Пн-Вс 09:00-20:00",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 30.0,
            "postamat_width": 32,
            "postamat_height": 39,
            "postamat_depth": 42,
            "postal_code": 460009,
            "latitude": 51.7899,
            "longitude": 55.072403,
            "address": "пр-т Братьев Коростелёвых, 43",
            "address_full": "460009, Россия, Оренбургская область, Оренбург, пр-т Братьев Коростелёвых, 43"
        },
        {
            "code": "ORN24",
            "uuid": "04bfc5ca-43ed-4f47-a920-8234ca21e6bc",
            "name": "На Чкалова 59",
            "address_comment": "30 метров от остановки \"Молодежная\" по нечетной стороне ул.Чкалова",
            "nearest_station": "Молодежная",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+79619069252,",
            "email": "r.kinzyagulov@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 50.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460000,
            "latitude": 51.773075,
            "longitude": 55.143417,
            "address": "ул.Чкалова, 59",
            "address_full": "460000, Россия, Оренбургская область, Оренбург, ул.Чкалова, 59"
        },
        {
            "code": "ORN47",
            "uuid": "c50b47c1-1c87-4973-b9af-c7ef6f8b6820",
            "name": "1948 Постамат Халва",
            "address_comment": "Магнит Косметик",
            "nearest_station": "Харьковская улица",
            "work_time": "Пн-Вс 10:00-21:00",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 30.0,
            "postamat_width": 32,
            "postamat_height": 39,
            "postamat_depth": 42,
            "postal_code": 460021,
            "latitude": 51.777695,
            "longitude": 55.138306,
            "address": "ул. Красногорская, 104",
            "address_full": "460021, Россия, Оренбургская область, Оренбург, ул. Красногорская, 104"
        },
        {
            "code": "ORN48",
            "uuid": "cc71869c-efb8-4a50-9661-b8640e4621a2",
            "name": "1950 Постамат Халва",
            "address_comment": "Магнит Косметик",
            "nearest_station": "Промысловый проезд",
            "work_time": "Пн-Вс 00:00-23:59",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 30.0,
            "postamat_width": 32,
            "postamat_height": 39,
            "postamat_depth": 42,
            "postal_code": 460051,
            "latitude": 51.779526,
            "longitude": 55.186676,
            "address": "пр. Промысловый, 19",
            "address_full": "460051, Россия, Оренбургская область, Оренбург, пр. Промысловый, 19"
        },
        {
            "code": "ORN25",
            "uuid": "3c25e244-302d-4d64-bfcc-09fd285cb4af",
            "name": "На Салмышской 6/1",
            "address_comment": "Остановка \"Проспект Дзержинского\", напротив магазина \"Русь\" угловой дом за сквером имени Дзержинского.",
            "nearest_station": "Проспект Дзержинского",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+79058876645,",
            "email": "naumkin.av@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 50.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460056,
            "latitude": 51.842434,
            "longitude": 55.136826,
            "address": "ул. Салмышская, 6/1",
            "address_full": "460056, Россия, Оренбургская область, Оренбург, ул. Салмышская, 6/1"
        },
        {
            "code": "ORN60",
            "uuid": "fc3cd5b6-7285-4807-9eed-4c59e706cb39",
            "name": "1960 Постамат Халва",
            "address_comment": "Войти в административное здание через центральный вход, на 1 этаже в супермаркете Магнит Косметик расположен постамат.",
            "nearest_station": "Главпочтамт",
            "work_time": "Пн-Вс 09:30-19:30",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 15.0,
            "postamat_width": 32,
            "postamat_height": 39,
            "postamat_depth": 42,
            "postal_code": 460000,
            "latitude": 51.76211,
            "longitude": 55.094692,
            "address": "ул. Кирова, 5",
            "address_full": "460000, Россия, Оренбургская область, Оренбург, ул. Кирова, 5"
        },
        {
            "code": "ORN74",
            "uuid": "8604dada-ac1a-446c-9db5-e7bd159a20ad",
            "name": "1941 Постамат Халва",
            "address_comment": "Почтомат Халва. Войти в ТЦ Салмышский пассаж через центральный вход, на 1 этаже в супермаркете Магнит Косметик расположен почтомат.",
            "nearest_station": "Остановка 19-й микрорайон.",
            "work_time": "Пн-Вс 10:00-21:00",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 15.0,
            "postamat_width": 32,
            "postamat_height": 39,
            "postamat_depth": 42,
            "postal_code": 460060,
            "latitude": 51.813633,
            "longitude": 55.175404,
            "address": "ул. Салмышская, 66/2",
            "address_full": "460060, Россия, Оренбургская область, Оренбург, ул. Салмышская, 66/2"
        },
        {
            "code": "ORN45",
            "uuid": "673e3099-524e-4965-a736-56ea6b0b13a2",
            "name": "5259 Постамат Халва",
            "address_comment": "Офис Совкомбанк",
            "nearest_station": "Автовокзал",
            "work_time": "Пн-Пт 09:00-19:00, Сб 09:00-17:00",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 30.0,
            "postamat_width": 35,
            "postamat_height": 45,
            "postamat_depth": 38,
            "postal_code": 460018,
            "latitude": 51.777733,
            "longitude": 55.104877,
            "address": "ул.Терешковой, 10",
            "address_full": "460018, Россия, Оренбургская область, Оренбург, ул.Терешковой, 10"
        },
        {
            "code": "ORN50",
            "uuid": "aa2343d3-fa5e-4ff8-aaf7-54b938b47332",
            "name": "3229 Постамат Халва",
            "address_comment": "Магнит Косметик",
            "nearest_station": "Ялтинская улица",
            "work_time": "Пн-Вс 10:00-21:00",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 30.0,
            "postamat_width": 39,
            "postamat_height": 19,
            "postamat_depth": 47,
            "postal_code": 460026,
            "latitude": 51.792816,
            "longitude": 55.137756,
            "address": "ул. Одесская, 111",
            "address_full": "460026, Россия, Оренбургская область, Оренбург, ул. Одесская, 111"
        },
        {
            "code": "ORN23",
            "uuid": "41c81d5b-2599-46b8-9f93-65ed03638352",
            "name": "ТЦ Радуга",
            "address_comment": "Остановка 23-й микрорайон, вход с торца ТЦ Радуга, цокольный этаж.",
            "nearest_station": "23-й микрорайон",
            "work_time": "Пн-Вс 10:00-20:00",
            "phones": "+79328438439,",
            "email": "e.ostrouhova@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 35.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460051,
            "latitude": 51.7757,
            "longitude": 55.1841,
            "address": "Пр-т. Гагарина, 48/1",
            "address_full": "460051, Россия, Оренбургская область, Оренбург, Пр-т. Гагарина, 48/1"
        },
        {
            "code": "ORN51",
            "uuid": "d7dcd298-bd48-40e5-94b4-244b970299de",
            "name": "1947 Постамат Халва",
            "address_comment": "Магнит Косметик",
            "nearest_station": "Улица 8-го Марта",
            "work_time": "Пн-Вс 09:30-21:00",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 30.0,
            "postamat_width": 32,
            "postamat_height": 39,
            "postamat_depth": 42,
            "postal_code": 460014,
            "latitude": 51.760296,
            "longitude": 55.111103,
            "address": "ул. Челюскинцев, 16",
            "address_full": "460014, Россия, Оренбургская область, Оренбург, ул. Челюскинцев, 16"
        },
        {
            "code": "ORN13",
            "uuid": "aafa35b7-de97-498d-a65c-140eb1360da0",
            "name": "Администрация на Чкалова",
            "address_comment": "Расположен в новом многоэтажном доме Кима 25 за администрацией Южного округа между ул. Чкалова и Туркестанская.",
            "nearest_station": "По ул. Чкалова – Парковская,  по ул. Туркестанская",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+73532430820,",
            "email": "a.klisch@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 75.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460001,
            "latitude": 51.771732,
            "longitude": 55.13173,
            "address": "Ул. Кима 25  (за Администрацией на Чкалова), .",
            "address_full": "460001, Россия, Оренбургская область, Оренбург, Ул. Кима 25  (за Администрацией на Чкалова), ."
        },
        {
            "code": "ORN20",
            "uuid": "90180aa6-7bf5-423d-9fe9-faeb22ee64b2",
            "name": "На Загородном шоссе, 1",
            "address_comment": null,
            "nearest_station": "10 Микрорайон",
            "work_time": "Пн-Вс 09:00-20:00",
            "phones": "+73532677669,",
            "email": "a.gilyazov@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": true,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": null,
            "weight_max": null,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460056,
            "latitude": 51.85317,
            "longitude": 55.143253,
            "address": "Загородное шоссе, 1",
            "address_full": "460056, Россия, Оренбургская область, Оренбург, Загородное шоссе, 1"
        },
        {
            "code": "ORN55",
            "uuid": "a7e4bf3a-85d7-437c-9c3d-a6a3f7070a92",
            "name": "На Туркестанской, 2А",
            "address_comment": "Выйти на остановке \"Туркестанская улица\", офис находится за ней.",
            "nearest_station": "ул. Туркестанская",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+73532323530,",
            "email": "is.makovsky@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 70.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460001,
            "latitude": 51.768215,
            "longitude": 55.11423,
            "address": "ул. Туркестанская, 2А",
            "address_full": "460001, Россия, Оренбургская область, Оренбург, ул. Туркестанская, 2А"
        },
        {
            "code": "ORN59",
            "uuid": "65e91cdb-0056-4500-b85b-a5d3ab6cfc92",
            "name": "На Северном проезде, 25стр2",
            "address_comment": "по улице Загородное шоссе, по улице Зеленко , улица проезд Северный",
            "nearest_station": "ул. Братьев Хусаиновых",
            "work_time": "Пн-Пт 10:00-21:00, Сб-Вс 10:00-19:00",
            "phones": "+79228110101,",
            "email": "e.shlyapnikova@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 100.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460052,
            "latitude": 51.83045,
            "longitude": 55.174576,
            "address": "СЕВЕРНЫЙ ПРОЕЗД, 25 стр. 2",
            "address_full": "460052, Россия, Оренбургская область, Оренбург, СЕВЕРНЫЙ ПРОЕЗД, 25 стр. 2"
        },
        {
            "code": "ORN11",
            "uuid": "26034a40-8e46-4b50-b8c2-6ac95d4c7883",
            "name": "На Победы 22",
            "address_comment": "Остановка «ОГУ», здание между домами 18 ( офис Сбербанка) и 20 (маг. Пятерочка), вход с торца дома",
            "nearest_station": "Оренбургский государственный университет",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+73532901018,",
            "email": "director-orenburg@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 50.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460018,
            "latitude": 51.776375,
            "longitude": 55.110744,
            "address": "пр-т Победы, 22 пом 1",
            "address_full": "460018, Россия, Оренбургская область, Оренбург, пр-т Победы, 22 пом 1"
        },
        {
            "code": "ORN66",
            "uuid": "b37d2f09-d909-4356-8e89-8f567c1855d7",
            "name": "4922 Постамат Халва",
            "address_comment": "Войти в отделение банка Совкомбанк через центральный вход, на 1 этаже расположен постамат.",
            "nearest_station": "Общежитие",
            "work_time": "Пн-Пт 09:00-19:00, Сб 09:00-18:00",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 15.0,
            "postamat_width": 35,
            "postamat_height": 45,
            "postamat_depth": 38,
            "postal_code": 460018,
            "latitude": 51.77445,
            "longitude": 55.106262,
            "address": "пр-т Победы, 9",
            "address_full": "460018, Россия, Оренбургская область, Оренбург, пр-т Победы, 9"
        },
        {
            "code": "ORN42",
            "uuid": "52f45561-c7f2-47d1-859e-903829f6d474",
            "name": "1961 Постамат Халва",
            "address_comment": "Магнит Косметик",
            "nearest_station": "Железнодорожная больница",
            "work_time": "Пн-Вс 10:00-19:30",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 30.0,
            "postamat_width": 32,
            "postamat_height": 39,
            "postamat_depth": 42,
            "postal_code": 460035,
            "latitude": 51.803,
            "longitude": 55.095016,
            "address": "ул. Пролетарская, 288/3",
            "address_full": "460035, Россия, Оренбургская область, Оренбург, ул. Пролетарская, 288/3"
        },
        {
            "code": "ORN52",
            "uuid": "071d90ca-03b2-4e2b-b7ef-e00386044e94",
            "name": "1939 Постамат Халва",
            "address_comment": "Магнит Косметик",
            "nearest_station": "Магазин Комета",
            "work_time": "Пн-Вс 10:00-21:00",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 30.0,
            "postamat_width": 32,
            "postamat_height": 39,
            "postamat_depth": 42,
            "postal_code": 460048,
            "latitude": 51.815857,
            "longitude": 55.144836,
            "address": "пр-кт Победы, 166",
            "address_full": "460048, Россия, Оренбургская область, Оренбург, пр-кт Победы, 166"
        },
        {
            "code": "ORN5",
            "uuid": "9de1369b-71ad-45b6-b808-434764b79976",
            "name": "На Ленинской",
            "address_comment": "Напротив остановки «Драмтеатр», если ехать из центра. Помещение бывшей пиццерии.",
            "nearest_station": "Драмтеатр",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+79328653540,",
            "email": "k.malysheva@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 35.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460000,
            "latitude": 51.762108,
            "longitude": 55.10658,
            "address": "ул. Ленинская, 50",
            "address_full": "460000, Россия, Оренбургская область, Оренбург, ул. Ленинская, 50"
        },
        {
            "code": "ORN57",
            "uuid": "180e7e0c-e76d-4fad-9b29-f28fd3cc5d49",
            "name": "3335 Постамат Халва",
            "address_comment": "Войти в супермаркет Магнит Косметик через центральный вход, на 1 этаже около входа расположен постамат",
            "nearest_station": "13-й микрорайон",
            "work_time": "Пн-Вс 10:00-21:00",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 30.0,
            "postamat_width": 35,
            "postamat_height": 45,
            "postamat_depth": 38,
            "postal_code": 460052,
            "latitude": 51.832226,
            "longitude": 55.15867,
            "address": "ул. Джангильдина, 16/2",
            "address_full": "460052, Россия, Оренбургская область, Оренбург, ул. Джангильдина, 16/2"
        },
        {
            "code": "ORN1",
            "uuid": "c18a1287-6470-4284-9f08-be01d2e4fda9",
            "name": "На Восточной ПВЗ",
            "address_comment": null,
            "nearest_station": "ул. Восточная",
            "work_time": "Пн-Пт 09:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+73532901060,+73532901050,",
            "email": "orenburg@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": null,
            "weight_max": null,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460021,
            "latitude": 51.783127,
            "longitude": 55.153774,
            "address": "ул. Восточная, 42/6",
            "address_full": "460021, Россия, Оренбургская область, Оренбург, ул. Восточная, 42/6"
        },
        {
            "code": "ORN9",
            "uuid": "e400d2c7-4f6e-4d3e-a955-9a6460dff768",
            "name": "На Беляевской",
            "address_comment": "По Беляевскому шоссе напротив поселка Весенний, красно-белое здание ТК “Astor”, отдельный вход с левого торца здания",
            "nearest_station": "Остановка Аптека, Остановка Пос. Карачи",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+79959075838,",
            "email": "naumkin.av@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 60.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460555,
            "latitude": 51.72009,
            "longitude": 55.136005,
            "address": "Беляевское шоссе, 5",
            "address_full": "460555, Россия, Оренбургская область, Оренбург, Беляевское шоссе, 5"
        },
        {
            "code": "ORN53",
            "uuid": "fc6028a0-7a24-43ba-bb12-9462235f4255",
            "name": "1957 Постамат Халва",
            "address_comment": "Магнит Косметик",
            "nearest_station": "Северный проезд",
            "work_time": "Пн-Вс 09:30-19:30",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 30.0,
            "postamat_width": 32,
            "postamat_height": 39,
            "postamat_depth": 42,
            "postal_code": 460060,
            "latitude": 51.823326,
            "longitude": 55.16319,
            "address": "СЕВЕРНЫЙ ПРОЕЗД, 12",
            "address_full": "460060, Россия, Оренбургская область, Оренбург, СЕВЕРНЫЙ ПРОЕЗД, 12"
        },
        {
            "code": "ORN8",
            "uuid": "ee0d1903-f273-436c-8625-ea865e88aefb",
            "name": "На Дзержинского",
            "address_comment": "50 метров от остановки «Брестская» по пр-ту Дзержинского, с торца магазина «Арлан»",
            "nearest_station": "«Брестская»",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+79619069252,",
            "email": "r.kinzyagulov@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 70.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460047,
            "latitude": 51.837753,
            "longitude": 55.13473,
            "address": "пр-т Дзержинского, 27/2",
            "address_full": "460047, Россия, Оренбургская область, Оренбург, пр-т Дзержинского, 27/2"
        },
        {
            "code": "ORN10",
            "uuid": "584266da-c715-4d35-9398-a90fbacf1f64",
            "name": "Времена года",
            "address_comment": null,
            "nearest_station": "Торговый центр МЕТРО",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+73532901019,",
            "email": "Orenburg@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 100.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460050,
            "latitude": 51.81539,
            "longitude": 55.133373,
            "address": "Рокоссовского, 31",
            "address_full": "460050, Россия, Оренбургская область, Оренбург, Рокоссовского, 31"
        },
        {
            "code": "ORN19",
            "uuid": "5494257d-932d-4721-8a96-28c976b7ce79",
            "name": "На Липовой 1",
            "address_comment": "Как добраться: автобус 62,40,59,65. От остановка Улица Джангильдина\n220 м,13-й микрорайон 820 м,Липовая улица 970 м",
            "nearest_station": "ул. Джангильдина",
            "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
            "phones": "+79033980518,",
            "email": "n.svyatkina@cdek.ru",
            "type": "PVZ",
            "owner_code": "CDEK",
            "take_only": false,
            "is_handout": true,
            "is_reception": true,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": true,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 75.0,
            "postamat_width": null,
            "postamat_height": null,
            "postamat_depth": null,
            "postal_code": 460052,
            "latitude": 51.83407,
            "longitude": 55.16388,
            "address": "ул. Липовая, 1",
            "address_full": "460052, Россия, Оренбургская область, Оренбург, ул. Липовая, 1"
        },
        {
            "code": "ORN67",
            "uuid": "47b4eb9e-1799-4873-9764-e3068cfc3eb0",
            "name": "4923 Постамат Халва",
            "address_comment": "Войти в отделение банка Совкомбанк через центральный вход, на 1 этаже расположен постамат.",
            "nearest_station": "Улица 60 лет Октября",
            "work_time": "Пн-Сб 10:00-19:00",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 15.0,
            "postamat_width": 35,
            "postamat_height": 45,
            "postamat_depth": 38,
            "postal_code": 460021,
            "latitude": 51.77501,
            "longitude": 55.150658,
            "address": "пр-т Гагарина, 10",
            "address_full": "460021, Россия, Оренбургская область, Оренбург, пр-т Гагарина, 10"
        },
        {
            "code": "ORN72",
            "uuid": "11e79d28-d295-489b-b31a-864b2100da2a",
            "name": "1956 Постамат Халва",
            "address_comment": "Почтомат Халва. Войти в ТЦ Парадис через центральный вход, на 1 этаже в супермаркете Магнит Косметик расположен почтомат.",
            "nearest_station": "Остановка Молодежная",
            "work_time": "Пн-Вс 10:00-19:30",
            "phones": "+74950090405,",
            "email": null,
            "type": "POSTAMAT",
            "owner_code": "Халва",
            "take_only": true,
            "is_handout": true,
            "is_reception": false,
            "is_ltl": false,
            "have_cashless": true,
            "have_cash": false,
            "allowed_cod": true,
            "weight_min": 0.0,
            "weight_max": 15.0,
            "postamat_width": 32,
            "postamat_height": 39,
            "postamat_depth": 42,
            "postal_code": 460058,
            "latitude": 51.772175,
            "longitude": 55.14108,
            "address": "ул. Чкалова, 55/1",
            "address_full": "460058, Россия, Оренбургская область, Оренбург, ул. Чкалова, 55/1"
        }
    ]


}


// выбирает Пункт Выдачи
let pickDeliveryPoint = () => {

    let deliveryPoint = {
        "code": "ORN58",
        "uuid": "1fd6a616-2716-4c82-947e-71f6cff3998d",
        "name": "На Березовой Ростоши 11",
        "address_comment": "От остановки Поликлиника 610 метров через Ледовый дворец",
        "nearest_station": "Поликлиника",
        "work_time": "Пн-Пт 10:00-20:00, Сб-Вс 10:00-18:00",
        "phones": "+79228496091,",
        "email": "e.ostrouhova@cdek.ru",
        "type": "PVZ",
        "owner_code": "CDEK",
        "take_only": false,
        "is_handout": true,
        "is_reception": true,
        "is_ltl": false,
        "have_cashless": true,
        "have_cash": true,
        "allowed_cod": true,
        "weight_min": 0.0,
        "weight_max": 50.0,
        "postamat_width": null,
        "postamat_height": null,
        "postamat_depth": null,
        "postal_code": 460008,
        "latitude": 51.78345,
        "longitude": 55.22484,
        "address": "ул. Березовая Ростошь, 11",
        "address_full": "460008, Россия, Оренбургская область, Оренбург, ул. Березовая Ростошь, 11"
    }
    console(deliveryPoint)

}
